name: Core-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CoreTests:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with: 
        vs-version: '[17.0,'
        msbuild-architecture: x64

    - name: Setup Engine 
      run: |
        python Tools/LkEngine-Setup.py

    - name: Build 
      run: |
        MSBuild.exe LkEngine.sln -property:Configuration=AutomationTest

    - name: Run tests
      run: |
        .\Binaries\AutomationTest-windows\LkEngine_AutomationTests\LkEngine_AutomationTests.exe TestResults.yaml

    - name: Evaluate test resuls
      run: |
        python LkEngine/Test/TestResultParser.py Binaries/AutomationTest-windows/LkEngine_AutomationTests/Results/TestResults.yaml

    - name: Upload Artifacts # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ./Binaries/AutomationTest-windows/LkEngine_AutomationTests/Results

    #- name: Deploy results
    #  uses: JamesIves/github-pages-deploy-action@v4
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    folder: ./Binaries/AutomationTest-windows/LkEngine_AutomationTests/Results
    #    branch: gh-pages

  Deploy-Test-Results:
    concurrency: ci-${{ github.ref }}
    needs: [CoreTests] # Depends on the first job to complete before running and uses ubuntu-latest instead of Windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine location
        run: |
          pwd
          ls -lh

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: TestResults

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'TestResults' # Must match the artifact name.

