name: Core-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CoreTests:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with: 
        vs-version: '[17.0,'
        msbuild-architecture: x64

    - name: Setup Engine 
      run: |
        python Tools/LkEngine-Setup.py

    - name: Build 
      run: |
        MSBuild.exe LkEngine.sln -property:Configuration=AutomationTest

    - name: Run tests
      run: |
        .\Binaries\AutomationTest-windows\LkEngine_AutomationTests\LkEngine_AutomationTests.exe TestResults.yaml

    - name: Evaluate test resuls
      run: |
        python LkEngine/Test/TestResultParser.py Binaries/AutomationTest-windows/LkEngine_AutomationTests/Results/TestResults.yaml

    - name: Publish test results
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Binaries/AutomationTest-windows/LkEngine_AutomationTests/Results

