name: Core-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CoreTests:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Upgrade Pip 
      run: |
        python -m pip install --upgrade pip

    - name: Locate MSBuild
      id: msbuild-locate
      run: |
        echo "Locating MSBuild..."
        $msbuild = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "MSBuild Path: $msbuild"
        echo "::set-output name=msbuild::$msbuild"
      shell: powershell

    - name: Build Engine 
      run: |
        python Tools/LkEngine-Setup.py

    - name: Run Tests
      run: |
        ./LkEngine/Binaries/AutomationTest-windows/LkEngine_AutomationTests.exe

    - name: Evaluate Test Result
      run: |
        python LkEngine/Test/TestResultParser.py

