name: Core-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CoreTests:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with: 
        vs-version: '[17.0,'
        msbuild-architecture: x64

    - name: Setup Engine 
      run: |
        python Tools/LkEngine-Setup.py

    - name: Build 
      run: |
        MSBuild.exe LkEngine.sln -property:Configuration=AutomationTest

    - name: Run Tests
      run: |
        ./LkEngine/LkEngine/Binaries/AutomationTest-windows/LkEngine_AutomationTests.exe

    - name: Evaluate Test Result
      run: |
        python LkEngine/Test/TestResultParser.py

