name: Core-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CoreTests:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Build Engine 
      run: |
        python Tools/LkEngine-Setup.py

    - name: Generate AutomationTest Project
      run: |
        External/premake/bin/premake5.exe --file=LkEngine.lua vs2022

    - name: Build AutomationTest Project
      run: |
        msbuild LkEngine.lua /p:Configuration=AutomationTest

    - name: Run Tests
      run: |
        ./LkEngine/Binaries/AutomationTest-windows/LkEngine_AutomationTests.exe

    - name: Evaluate Test Result
      run: |
        python LkEngine/Test/TestResultParser.py

    #- name: Upload Test Summary
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: Test-Summary
    #    path: Test-Summary.json
