name: LkEngine-AutomationTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
        choco install ninja --yes

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Debug