name: LkEngine-AutomationTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  WorkflowTest:
    runs-on: windows-latest

    steps:
    - name: Code Checkout 
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python Tools/LkEngine-Setup.py

    - name: Build
      run: |
        mkdir Build

    - name: Run Test 
      run: |
        cd Build
