name: LkEngine-AutomationTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  EngineSetup:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Upgrade pip 
      run: |
        python -m pip install --upgrade pip

    - name: Setup LkEngine 
      run: |
        python Tools/LkEngine-Setup.py
