name: LkEngine-AutomationTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: msvc
        cpp-version: 20

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
        choco install ninja --yes # Optional if you're using Ninja

    - name: Configure build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..

    - name: Build project
      run: |
        cd build
        cmake --build . --config Debug

    - name: Run tests
      run: |
        cd build
        ctest -C Debug --output-on-failure